#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
JAVAC         = $(SPLICE_JAVAC)
JAR           = jar
JAVACFLAGS    = $(GENFLAGS)
CLASSEXT      = .class
CLASSDIR      = classes/
OUTPUT_OPTION = -d $(CLASSDIR)
COMPILE.java  = $(JAVAC) $(JAVACFLAGS) -cp $(JAVACCPATH) 
JAVACCPATH    = "$(SPLICE_EXTRA_CP):Saj_Throughput_Types.jar:$(CLASSDIR):../../../../jar/dcpssaj.jar:"
MAKEFILE      = Makefile.Saj_Throughput_Publisher
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
GENFLAGS      =  
CLASSES       =  $(CLASSDIR)publisher$(CLASSEXT) $(CLASSDIR)Publisher_impl$(CLASSEXT) $(CLASSDIR)PubEntities$(CLASSEXT) $(CLASSDIR)ExampleUtilities$(CLASSEXT) $(CLASSDIR)ExampleError$(CLASSEXT)
JARCLASSES    =  publisher$(CLASSEXT) Publisher_impl$(CLASSEXT) PubEntities$(CLASSEXT) ExampleUtilities$(CLASSEXT) ExampleError$(CLASSEXT)
JAREXT        = .jar
MAINCLASS     = publisher
JARFILE       = $(LTARGETDIR)$(LIBPREFIX)Saj_Throughput_Publisher$(LIBSUFFIX)$(JAREXT)
MANIFEST      = Saj_Throughput_Publisher.manifest
JARFLAGS      = cvfm
SRC           = publisher.java Publisher_impl.java PubEntities.java ExampleUtilities.java ExampleError.java
CLASSES       += classes/Publisher_impl*.class
JARCLASSES    += Publisher_impl*.class
JARCLASSES    += ExampleUtilities*.class


#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(JARFILE)

$(JARFILE): $(CLASSES) $(CLASSDIR)$(MANIFEST)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	cd $(CLASSDIR) && $(JAR) $(JARFLAGS) $(JARFILE) $(MANIFEST) $(JARCLASSES) 
	$(MV) $(CLASSDIR)/$(JARFILE) .

$(CLASSDIR)$(MANIFEST):
	echo Class-Path: Saj_Throughput_Types.jar ../../../../jar/dcpssaj.jar > $(CLASSDIR)$(MANIFEST)
	echo Main-Class: $(MAINCLASS) >> $(CLASSDIR)$(MANIFEST)

generated: $(GENERATED_DIRTY)
	@-:

$(CLASSDIR)publisher$(CLASSEXT): publisher.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) publisher.java

$(CLASSDIR)Publisher_impl$(CLASSEXT): Publisher_impl.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) Publisher_impl.java

$(CLASSDIR)PubEntities$(CLASSEXT): PubEntities.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) PubEntities.java

$(CLASSDIR)ExampleUtilities$(CLASSEXT): ExampleUtilities.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) ExampleUtilities.java

$(CLASSDIR)ExampleError$(CLASSEXT): ExampleError.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) ExampleError.java

clean:
	-$(RM) $(CLASSES)

realclean: clean
	-$(RM) $(BIN)
	-$(RM) $(CLASSDIR)$(MANIFEST)

check-syntax:
	$(COMPILE.java) $(EXPORTFLAGS) $(CHK_SOURCES)

