# -*-Makefile-*-
#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------

CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(PICFLAGS) $(GENFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CCFLAGS        =  
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -D_REENTRANT -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=500 -Wall -Wno-unused-function -I"../../../../include" -I"../../../../include/sys" -I"$(BOOST_ROOT)/." -I"../../../../include/dcps/C++/isocpp" -I"../../../../include/dcps/C++/SACPP" -I"." -I"../../../../examples/include" -I"../../../../examples"
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"." -L"../../../../lib" -Wl,-rpath,\$$ORIGIN -Wl,-rpath,\$$ORIGIN/../../../../lib
CCC           = $(CXX)
MAKEFILE      = Makefile.ISO_Cxx_Ownership_Types
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -O3 -DNDEBUG
LDLIBS        = -l"dcpsisocpp$(LIBSUFFIX)" -l"ddskernel" -ldl $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so))))) -lpthread
OBJS          = .obj$(CFG)/OwnershipDataSplDcps$(OBJEXT) .obj$(CFG)/OwnershipDataDcps_impl$(OBJEXT) .obj$(CFG)/OwnershipData$(OBJEXT) .obj$(CFG)/OwnershipDataDcps$(OBJEXT)
AREXT         = .a
LIB           = $(LTARGETDIR)$(LIBPREFIX)ISO_Cxx_Ownership_Types$(LIBSUFFIX)$(AREXT)
SOEXT         = .so
SHTARGETDIR   = ./
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)ISO_Cxx_Ownership_Types$(LIBSUFFIX)$(SOEXT)
SHFLAGS       = -shared
SRC           = OwnershipDataSplDcps.cpp OwnershipDataDcps_impl.cpp OwnershipData.cpp OwnershipDataDcps.cpp
LINK.cc       = $(LD) $(LDFLAGS)
DYNAMICFLAGS  = -DOSPL_BUILDEXAMPLE_LIB
EXPORTFLAGS   = $(DYNAMICFLAGS)

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(SHLIB)

$(SHLIB): $(OBJS)
	@$(TESTDIRSTART) "$(SHTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(SHTARGETDIR)"
	$(LINK.cc) $(SHFLAGS) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

$(LIB): $(OBJS)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	$(AR) $(ARFLAGS) $(LIB) $(OBJS) 

GENERATED_DIRTY = OwnershipData.h OwnershipDataSplDcps.cpp OwnershipDataDcps_impl.cpp OwnershipData.cpp OwnershipDataDcps.cpp OwnershipDataDcps.h OwnershipData_DCPS.hpp OwnershipDataDcps_impl.h OwnershipDataSplDcps.h

export DYLD_LIBRARY_PATH := $(DYLD_LIBRARY_PATH):../../../../bin:../../../../lib
export LD_LIBRARY_PATH   := $(LD_LIBRARY_PATH):../../../../bin:../../../../lib
export SHLIB_PATH        := $(SHLIB_PATH):../../../../bin:../../../../lib
export LIBPATH           := $(LIBPATH):../../../../bin:../../../../lib
export PATH              := $(PATH):../../../../bin:../../../../lib

.NOTPARALLEL:
OwnershipData.h OwnershipDataSplDcps.cpp OwnershipDataDcps_impl.cpp OwnershipData.cpp OwnershipDataDcps.cpp OwnershipDataDcps.h OwnershipData_DCPS.hpp OwnershipDataDcps_impl.h OwnershipDataSplDcps.h: ../idl/OwnershipData.idl
	"../../../../bin/idlpp" -I "../../../../etc/idl" -l isocpp ../idl/OwnershipData.idl

.PRECIOUS: $(GENERATED_DIRTY)
$(OBJS): $(GENERATED_DIRTY)

generated: $(GENERATED_DIRTY)
	@-:

.obj$(CFG)/OwnershipDataSplDcps$(OBJEXT): OwnershipDataSplDcps.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) OwnershipDataSplDcps.cpp

.obj$(CFG)/OwnershipDataDcps_impl$(OBJEXT): OwnershipDataDcps_impl.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) OwnershipDataDcps_impl.cpp

.obj$(CFG)/OwnershipData$(OBJEXT): OwnershipData.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) OwnershipData.cpp

.obj$(CFG)/OwnershipDataDcps$(OBJEXT): OwnershipDataDcps.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) OwnershipDataDcps.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(SHLIB) $(LIB)
	-$(RM) $(GENERATED_DIRTY)
	-$(RM) .obj$(CFG)/

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) $(CHK_SOURCES)

