#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
JAVAC         = $(SPLICE_JAVAC)
JAR           = jar
JAVACFLAGS    = $(GENFLAGS)
CLASSEXT      = .class
CLASSDIR      = classes/
OUTPUT_OPTION = -d $(CLASSDIR)
COMPILE.java  = $(JAVAC) $(JAVACFLAGS) -cp $(JAVACCPATH) 
JAVACCPATH    = "$(SPLICE_EXTRA_CP):$(CLASSDIR):../../../../../jar/dcpssaj.jar:"
MAKEFILE      = Makefile.saj_contentfilteredtopic_types
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
GENFLAGS      =  
CLASSES       =  $(CLASSDIR)StockMarket/*$(CLASSEXT)
JARCLASSES    =  StockMarket/*$(CLASSEXT)
JAREXT        = .jar
JARFILE       = $(LTARGETDIR)$(LIBPREFIX)saj_contentfilteredtopic_types$(LIBSUFFIX)$(JAREXT)
MANIFEST      = saj_contentfilteredtopic_types.manifest
JARFLAGS      = cvfm
SRC           = StockMarket/*.java

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(JARFILE)

$(JARFILE): $(CLASSES) $(CLASSDIR)$(MANIFEST)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	cd $(CLASSDIR) && $(JAR) $(JARFLAGS) $(JARFILE) $(MANIFEST) $(JARCLASSES) 
	$(MV) $(CLASSDIR)/$(JARFILE) .

$(CLASSDIR)$(MANIFEST):
	echo Class-Path: ../../../../../jar/dcpssaj.jar > $(CLASSDIR)$(MANIFEST)

GENERATED_DIRTY = StockMarket

StockMarket: ../../idl/ContentFilteredTopicData.idl
	"../../../../../bin/idlpp" -I "../../../../../etc/idl" -l java ../../idl/ContentFilteredTopicData.idl

.PRECIOUS: $(GENERATED_DIRTY)
$(CLASSES): $(GENERATED_DIRTY)

generated: $(GENERATED_DIRTY)
	@-:

$(CLASSDIR)StockMarket/*$(CLASSEXT): StockMarket
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) StockMarket/*.java

clean:
	-$(RM) $(CLASSES)

realclean: clean
	-$(RM) $(SHLIB) $(JARFILE)
	-$(RM) $(GENERATED_DIRTY)
	-$(RM) $(CLASSDIR)$(MANIFEST)

check-syntax:
	$(COMPILE.java) $(EXPORTFLAGS) $(CHK_SOURCES)

