//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_namedQosTypesDcps.h
//  Source: dds_namedQosTypesDcps.idl
//  Generated: Thu Mar 22 16:45:49 2018
//  OpenSplice 6.7.171127OSS
//  
//******************************************************************
#ifndef _DDS_NAMEDQOSTYPESDCPS_H_
#define _DDS_NAMEDQOSTYPESDCPS_H_

#include "sacpp_mapping.h"
#include "dds_dcps.h"
#include "dds_dcps_builtintopics.h"
#include "dds_namedQosTypes.h"






#endif
